// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// Rxjs
import 'rxjs';
import 'reflect-metadata';
//# sourceMappingURL=vendor.js.map